{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "961c12c9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "1.1 Loading the dataset\n",
    "data = pd.read_csv('../input/zomato-bangalore-restaurants/zomato.csv')\n",
    "data\n",
    "url\taddress\tname\tonline_order\tbook_table\trate\tvotes\tphone\tlocation\trest_type\tdish_liked\tcuisines\tapprox_cost(for two people)\treviews_list\tmenu_item\tlisted_in(type)\tlisted_in(city)\n",
    "0\thttps://www.zomato.com/bangalore/jalsa-banasha...\t942, 21st Main Road, 2nd Stage, Banashankari, ...\tJalsa\tYes\tYes\t4.1/5\t775\t080 42297555\\r\\n+91 9743772233\tBanashankari\tCasual Dining\tPasta, Lunch Buffet, Masala Papad, Paneer Laja...\tNorth Indian, Mughlai, Chinese\t800\t[('Rated 4.0', 'RATED\\n A beautiful place to ...\t[]\tBuffet\tBanashankari\n",
    "1\thttps://www.zomato.com/bangalore/spice-elephan...\t2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...\tSpice Elephant\tYes\tNo\t4.1/5\t787\t080 41714161\tBanashankari\tCasual Dining\tMomos, Lunch Buffet, Chocolate Nirvana, Thai G...\tChinese, North Indian, Thai\t800\t[('Rated 4.0', 'RATED\\n Had been here for din...\t[]\tBuffet\tBanashankari\n",
    "2\thttps://www.zomato.com/SanchurroBangalore?cont...\t1112, Next to KIMS Medical College, 17th Cross...\tSan Churro Cafe\tYes\tNo\t3.8/5\t918\t+91 9663487993\tBanashankari\tCafe, Casual Dining\tChurros, Cannelloni, Minestrone Soup, Hot Choc...\tCafe, Mexican, Italian\t800\t[('Rated 3.0', \"RATED\\n Ambience is not that ...\t[]\tBuffet\tBanashankari\n",
    "3\thttps://www.zomato.com/bangalore/addhuri-udupi...\t1st Floor, Annakuteera, 3rd Stage, Banashankar...\tAddhuri Udupi Bhojana\tNo\tNo\t3.7/5\t88\t+91 9620009302\tBanashankari\tQuick Bites\tMasala Dosa\tSouth Indian, North Indian\t300\t[('Rated 4.0', \"RATED\\n Great food and proper...\t[]\tBuffet\tBanashankari\n",
    "4\thttps://www.zomato.com/bangalore/grand-village...\t10, 3rd Floor, Lakshmi Associates, Gandhi Baza...\tGrand Village\tNo\tNo\t3.8/5\t166\t+91 8026612447\\r\\n+91 9901210005\tBasavanagudi\tCasual Dining\tPanipuri, Gol Gappe\tNorth Indian, Rajasthani\t600\t[('Rated 4.0', 'RATED\\n Very good restaurant ...\t[]\tBuffet\tBanashankari\n",
    "...\t...\t...\t...\t...\t...\t...\t...\t...\t...\t...\t...\t...\t...\t...\t...\t...\t...\n",
    "51712\thttps://www.zomato.com/bangalore/best-brews-fo...\tFour Points by Sheraton Bengaluru, 43/3, White...\tBest Brews - Four Points by Sheraton Bengaluru...\tNo\tNo\t3.6 /5\t27\t080 40301477\tWhitefield\tBar\tNaN\tContinental\t1,500\t[('Rated 5.0', \"RATED\\n Food and service are ...\t[]\tPubs and bars\tWhitefield\n",
    "51713\thttps://www.zomato.com/bangalore/vinod-bar-and...\tNumber 10, Garudachar Palya, Mahadevapura, Whi...\tVinod Bar And Restaurant\tNo\tNo\tNaN\t0\t+91 8197675843\tWhitefield\tBar\tNaN\tFinger Food\t600\t[]\t[]\tPubs and bars\tWhitefield\n",
    "51714\thttps://www.zomato.com/bangalore/plunge-sherat...\tSheraton Grand Bengaluru Whitefield Hotel & Co...\tPlunge - Sheraton Grand Bengaluru Whitefield H...\tNo\tNo\tNaN\t0\tNaN\tWhitefield\tBar\tNaN\tFinger Food\t2,000\t[]\t[]\tPubs and bars\tWhitefield\n",
    "51715\thttps://www.zomato.com/bangalore/chime-sherato...\tSheraton Grand Bengaluru Whitefield Hotel & Co...\tChime - Sheraton Grand Bengaluru Whitefield Ho...\tNo\tYes\t4.3 /5\t236\t080 49652769\tITPL Main Road, Whitefield\tBar\tCocktails, Pizza, Buttermilk\tFinger Food\t2,500\t[('Rated 4.0', 'RATED\\n Nice and friendly pla...\t[]\tPubs and bars\tWhitefield\n",
    "51716\thttps://www.zomato.com/bangalore/the-nest-the-...\tITPL Main Road, KIADB Export Promotion Industr...\tThe Nest - The Den Bengaluru\tNo\tNo\t3.4 /5\t13\t+91 8071117272\tITPL Main Road, Whitefield\tBar, Casual Dining\tNaN\tFinger Food, North Indian, Continental\t1,500\t[('Rated 5.0', 'RATED\\n Great ambience , look...\t[]\tPubs and bars\tWhitefield\n",
    "51717 rows × 17 columns\n",
    "\n",
    "1.2 checking the shape of dataset\n",
    "data.shape\n",
    "(51717, 17)\n",
    "there are total 51717 samples with 17 features.\n",
    "data.columns\n",
    "Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',\n",
    "       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',\n",
    "       'approx_cost(for two people)', 'reviews_list', 'menu_item',\n",
    "       'listed_in(type)', 'listed_in(city)'],\n",
    "      dtype='object')\n",
    "1.3 checking the datatypes\n",
    "data.info()\n",
    "<class 'pandas.core.frame.DataFrame'>\n",
    "RangeIndex: 51717 entries, 0 to 51716\n",
    "Data columns (total 17 columns):\n",
    " #   Column                       Non-Null Count  Dtype \n",
    "---  ------                       --------------  ----- \n",
    " 0   url                          51717 non-null  object\n",
    " 1   address                      51717 non-null  object\n",
    " 2   name                         51717 non-null  object\n",
    " 3   online_order                 51717 non-null  object\n",
    " 4   book_table                   51717 non-null  object\n",
    " 5   rate                         43942 non-null  object\n",
    " 6   votes                        51717 non-null  int64 \n",
    " 7   phone                        50509 non-null  object\n",
    " 8   location                     51696 non-null  object\n",
    " 9   rest_type                    51490 non-null  object\n",
    " 10  dish_liked                   23639 non-null  object\n",
    " 11  cuisines                     51672 non-null  object\n",
    " 12  approx_cost(for two people)  51371 non-null  object\n",
    " 13  reviews_list                 51717 non-null  object\n",
    " 14  menu_item                    51717 non-null  object\n",
    " 15  listed_in(type)              51717 non-null  object\n",
    " 16  listed_in(city)              51717 non-null  object\n",
    "dtypes: int64(1), object(16)\n",
    "memory usage: 6.7+ MB\n",
    "there are so many object type columns, we have to convert them into numeric type. letter we will convert oject dtype to numeric type\n",
    "2. Data Cleaning\n",
    "2.1 checking the missing values\n",
    "data.isnull().sum()\n",
    "url                                0\n",
    "address                            0\n",
    "name                               0\n",
    "online_order                       0\n",
    "book_table                         0\n",
    "rate                            7775\n",
    "votes                              0\n",
    "phone                           1208\n",
    "location                          21\n",
    "rest_type                        227\n",
    "dish_liked                     28078\n",
    "cuisines                          45\n",
    "approx_cost(for two people)      346\n",
    "reviews_list                       0\n",
    "menu_item                          0\n",
    "listed_in(type)                    0\n",
    "listed_in(city)                    0\n",
    "dtype: int64\n",
    "there are so many null values.we can clearly see that in the 'rate', 'phone', 'location', 'rest_type', 'dish_liked', 'cuisines' and 'approx_cost(for two people)' these columns have missing values.So firstly we have to handle the missing values.\n",
    "2.2 Removing the unnecessary columns form data\n",
    "df = data.drop(['url', 'phone'], axis = 1) # dropped 'url' and 'phone' columns\n",
    "df.head()\n",
    "address\tname\tonline_order\tbook_table\trate\tvotes\tlocation\trest_type\tdish_liked\tcuisines\tapprox_cost(for two people)\treviews_list\tmenu_item\tlisted_in(type)\tlisted_in(city)\n",
    "0\t942, 21st Main Road, 2nd Stage, Banashankari, ...\tJalsa\tYes\tYes\t4.1/5\t775\tBanashankari\tCasual Dining\tPasta, Lunch Buffet, Masala Papad, Paneer Laja...\tNorth Indian, Mughlai, Chinese\t800\t[('Rated 4.0', 'RATED\\n A beautiful place to ...\t[]\tBuffet\tBanashankari\n",
    "1\t2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...\tSpice Elephant\tYes\tNo\t4.1/5\t787\tBanashankari\tCasual Dining\tMomos, Lunch Buffet, Chocolate Nirvana, Thai G...\tChinese, North Indian, Thai\t800\t[('Rated 4.0', 'RATED\\n Had been here for din...\t[]\tBuffet\tBanashankari\n",
    "2\t1112, Next to KIMS Medical College, 17th Cross...\tSan Churro Cafe\tYes\tNo\t3.8/5\t918\tBanashankari\tCafe, Casual Dining\tChurros, Cannelloni, Minestrone Soup, Hot Choc...\tCafe, Mexican, Italian\t800\t[('Rated 3.0', \"RATED\\n Ambience is not that ...\t[]\tBuffet\tBanashankari\n",
    "3\t1st Floor, Annakuteera, 3rd Stage, Banashankar...\tAddhuri Udupi Bhojana\tNo\tNo\t3.7/5\t88\tBanashankari\tQuick Bites\tMasala Dosa\tSouth Indian, North Indian\t300\t[('Rated 4.0', \"RATED\\n Great food and proper...\t[]\tBuffet\tBanashankari\n",
    "4\t10, 3rd Floor, Lakshmi Associates, Gandhi Baza...\tGrand Village\tNo\tNo\t3.8/5\t166\tBasavanagudi\tCasual Dining\tPanipuri, Gol Gappe\tNorth Indian, Rajasthani\t600\t[('Rated 4.0', 'RATED\\n Very good restaurant ...\t[]\tBuffet\tBanashankari\n",
    "2.3 handling the null or missing values\n",
    "df.dropna(inplace = True)\n",
    "df.isnull().sum()\n",
    "address                        0\n",
    "name                           0\n",
    "online_order                   0\n",
    "book_table                     0\n",
    "rate                           0\n",
    "votes                          0\n",
    "location                       0\n",
    "rest_type                      0\n",
    "dish_liked                     0\n",
    "cuisines                       0\n",
    "approx_cost(for two people)    0\n",
    "reviews_list                   0\n",
    "menu_item                      0\n",
    "listed_in(type)                0\n",
    "listed_in(city)                0\n",
    "dtype: int64\n",
    "Now there is no null values\n",
    "2.4 checking the duplicates & handling the duplicates values\n",
    "df.duplicated().sum()\n",
    "11\n",
    "df.drop_duplicates(inplace = True)\n",
    "df.duplicated().sum()\n",
    "0\n",
    "Now there are no duplicate values.\n",
    " \n",
    "2.5 Renaming the columns appropriately\n",
    "df = df.rename(columns = {'approx_cost(for two people)':'cost',\n",
    "                         'listed_in(type)':'type', 'listed_in(city)': 'city'})\n",
    "df.head()\n",
    "address\tname\tonline_order\tbook_table\trate\tvotes\tlocation\trest_type\tdish_liked\tcuisines\tcost\treviews_list\tmenu_item\ttype\tcity\n",
    "0\t942, 21st Main Road, 2nd Stage, Banashankari, ...\tJalsa\tYes\tYes\t4.1/5\t775\tBanashankari\tCasual Dining\tPasta, Lunch Buffet, Masala Papad, Paneer Laja...\tNorth Indian, Mughlai, Chinese\t800\t[('Rated 4.0', 'RATED\\n A beautiful place to ...\t[]\tBuffet\tBanashankari\n",
    "1\t2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...\tSpice Elephant\tYes\tNo\t4.1/5\t787\tBanashankari\tCasual Dining\tMomos, Lunch Buffet, Chocolate Nirvana, Thai G...\tChinese, North Indian, Thai\t800\t[('Rated 4.0', 'RATED\\n Had been here for din...\t[]\tBuffet\tBanashankari\n",
    "2\t1112, Next to KIMS Medical College, 17th Cross...\tSan Churro Cafe\tYes\tNo\t3.8/5\t918\tBanashankari\tCafe, Casual Dining\tChurros, Cannelloni, Minestrone Soup, Hot Choc...\tCafe, Mexican, Italian\t800\t[('Rated 3.0', \"RATED\\n Ambience is not that ...\t[]\tBuffet\tBanashankari\n",
    "3\t1st Floor, Annakuteera, 3rd Stage, Banashankar...\tAddhuri Udupi Bhojana\tNo\tNo\t3.7/5\t88\tBanashankari\tQuick Bites\tMasala Dosa\tSouth Indian, North Indian\t300\t[('Rated 4.0', \"RATED\\n Great food and proper...\t[]\tBuffet\tBanashankari\n",
    "4\t10, 3rd Floor, Lakshmi Associates, Gandhi Baza...\tGrand Village\tNo\tNo\t3.8/5\t166\tBasavanagudi\tCasual Dining\tPanipuri, Gol Gappe\tNorth Indian, Rajasthani\t600\t[('Rated 4.0', 'RATED\\n Very good restaurant ...\t[]\tBuffet\tBanashankari\n",
    "Sucessfully rename the columns\n",
    "2.6 cleaning the \"cost\" column\n",
    "df['cost'].unique()\n",
    "array(['800', '300', '600', '700', '550', '500', '450', '650', '400',\n",
    "       '750', '200', '850', '1,200', '150', '350', '250', '1,500',\n",
    "       '1,300', '1,000', '100', '900', '1,100', '1,600', '950', '230',\n",
    "       '1,700', '1,400', '1,350', '2,200', '2,000', '1,800', '1,900',\n",
    "       '180', '330', '2,500', '2,100', '3,000', '2,800', '3,400', '40',\n",
    "       '1,250', '3,500', '4,000', '2,400', '1,450', '3,200', '6,000',\n",
    "       '1,050', '4,100', '2,300', '120', '2,600', '5,000', '3,700',\n",
    "       '1,650', '2,700', '4,500'], dtype=object)\n",
    "here we can see that data point is string type and some values like 5,000 6,000 have comma(,). we have to remove that ',' from the values and we have convert them into numeric type.\n",
    "df['cost'] = df['cost'].apply(lambda x:x.replace(',', '')) # lo\n",
    "df['cost'] = df['cost'].astype(float)\n",
    "\n",
    "df['cost'].unique()\n",
    "array([ 800.,  300.,  600.,  700.,  550.,  500.,  450.,  650.,  400.,\n",
    "        750.,  200.,  850., 1200.,  150.,  350.,  250., 1500., 1300.,\n",
    "       1000.,  100.,  900., 1100., 1600.,  950.,  230., 1700., 1400.,\n",
    "       1350., 2200., 2000., 1800., 1900.,  180.,  330., 2500., 2100.,\n",
    "       3000., 2800., 3400.,   40., 1250., 3500., 4000., 2400., 1450.,\n",
    "       3200., 6000., 1050., 4100., 2300.,  120., 2600., 5000., 3700.,\n",
    "       1650., 2700., 4500.])\n",
    "Now sucessfully we converted the values into numeric type\n",
    "2.7 handling the rate columns\n",
    "df['rate'].unique()\n",
    "array(['4.1/5', '3.8/5', '3.7/5', '4.6/5', '4.0/5', '4.2/5', '3.9/5',\n",
    "       '3.0/5', '3.6/5', '2.8/5', '4.4/5', '3.1/5', '4.3/5', '2.6/5',\n",
    "       '3.3/5', '3.5/5', '3.8 /5', '3.2/5', '4.5/5', '2.5/5', '2.9/5',\n",
    "       '3.4/5', '2.7/5', '4.7/5', 'NEW', '2.4/5', '2.2/5', '2.3/5',\n",
    "       '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5', '2.9 /5',\n",
    "       '2.7 /5', '2.5 /5', '2.6 /5', '4.5 /5', '4.3 /5', '3.7 /5',\n",
    "       '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5', '3.4 /5', '3.6 /5',\n",
    "       '3.3 /5', '4.6 /5', '4.9 /5', '3.2 /5', '3.0 /5', '2.8 /5',\n",
    "       '3.5 /5', '3.1 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5',\n",
    "       '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)\n",
    "here rating column also string type. we have to convert them into numeric type. we have to remove the '/5' form given values. there is 'NEW' value which make no sense. SO we have to remove that values.\n",
    "df = df.loc[df.rate != 'NEW'] # geting rid of 'NEW'\n",
    "df['rate'].unique()\n",
    "array(['4.1/5', '3.8/5', '3.7/5', '4.6/5', '4.0/5', '4.2/5', '3.9/5',\n",
    "       '3.0/5', '3.6/5', '2.8/5', '4.4/5', '3.1/5', '4.3/5', '2.6/5',\n",
    "       '3.3/5', '3.5/5', '3.8 /5', '3.2/5', '4.5/5', '2.5/5', '2.9/5',\n",
    "       '3.4/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5', '4.8/5',\n",
    "       '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5', '2.9 /5', '2.7 /5',\n",
    "       '2.5 /5', '2.6 /5', '4.5 /5', '4.3 /5', '3.7 /5', '4.4 /5',\n",
    "       '4.9/5', '2.1/5', '2.0/5', '1.8/5', '3.4 /5', '3.6 /5', '3.3 /5',\n",
    "       '4.6 /5', '4.9 /5', '3.2 /5', '3.0 /5', '2.8 /5', '3.5 /5',\n",
    "       '3.1 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5', '2.1 /5',\n",
    "       '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)\n",
    "df['rate'] = df['rate'].apply(lambda x:x.replace('/5', ''))\n",
    "\n",
    "df['rate'].unique()\n",
    "array(['4.1', '3.8', '3.7', '4.6', '4.0', '4.2', '3.9', '3.0', '3.6',\n",
    "       '2.8', '4.4', '3.1', '4.3', '2.6', '3.3', '3.5', '3.8 ', '3.2',\n",
    "       '4.5', '2.5', '2.9', '3.4', '2.7', '4.7', '2.4', '2.2', '2.3',\n",
    "       '4.8', '3.9 ', '4.2 ', '4.0 ', '4.1 ', '2.9 ', '2.7 ', '2.5 ',\n",
    "       '2.6 ', '4.5 ', '4.3 ', '3.7 ', '4.4 ', '4.9', '2.1', '2.0', '1.8',\n",
    "       '3.4 ', '3.6 ', '3.3 ', '4.6 ', '4.9 ', '3.2 ', '3.0 ', '2.8 ',\n",
    "       '3.5 ', '3.1 ', '4.8 ', '2.3 ', '4.7 ', '2.4 ', '2.1 ', '2.2 ',\n",
    "       '2.0 ', '1.8 '], dtype=object)\n",
    "df['rate'] = df['rate'].apply(lambda x: float(x))\n",
    "df['rate']\n",
    "0        4.1\n",
    "1        4.1\n",
    "2        3.8\n",
    "3        3.7\n",
    "4        3.8\n",
    "        ... \n",
    "51705    3.8\n",
    "51707    3.9\n",
    "51708    2.8\n",
    "51711    2.5\n",
    "51715    4.3\n",
    "Name: rate, Length: 23248, dtype: float64\n",
    "Now our data is cleaned and we can perform visulization\n",
    "3. Data Visulaization\n",
    "3.1 Most famous restaurant chains in banaglore\n",
    "plt.figure(figsize = (17,10))\n",
    "chains = df['name'].value_counts()[:20]\n",
    "sns.barplot(x = chains, y=  chains.index,  palette= 'deep')\n",
    "plt.title('Most famous restaurants chains in bangalore')\n",
    "plt.xlabel('Number of outlets')\n",
    "plt.show()\n",
    "\n",
    "Insights:\n",
    "\n",
    "'Onesta', 'Empire Restaurant' & 'KFC' are the most famous restaurant in bangalore.\n",
    " \n",
    "3.2 checking online order or not\n",
    "v = df['online_order'].value_counts()\n",
    "fig = plt.gcf()\n",
    "fig.set_size_inches((10,6))\n",
    "cmap = plt.get_cmap('Set3')\n",
    "color = cmap(np.arange(len(v)))\n",
    "\n",
    "plt.pie(v, labels = v.index, wedgeprops= dict(width = 0.6),autopct = '%0.02f', shadow = True, colors=  color)\n",
    "plt.title('Online orders', fontsize = 20)\n",
    "plt.show()\n",
    "\n",
    "Insight:\n",
    "\n",
    "Most Restaurants offer option for online order and delivery.\n",
    "3.3 Book table or not\n",
    "v = df['book_table'].value_counts()\n",
    "\n",
    "fig = plt.gcf()\n",
    "fig.set_size_inches((8,6))\n",
    "cmap = plt.get_cmap('Set1')\n",
    "color = cmap(np.arange(len(v)))\n",
    "\n",
    "plt.pie(v, labels = v.index, wedgeprops= dict(width = 0.6),autopct = '%0.02f', shadow = True, colors=  color)\n",
    "plt.title('Book Table', fontsize = 20)\n",
    "plt.show()\n",
    "\n",
    "Insight:\n",
    "\n",
    "Most of restaurants doesn't offer table booking.\n",
    "3.4 Rating Distribution\n",
    "plt.figure(figsize = (9,7))\n",
    "sns.distplot(df['rate'])\n",
    "plt.title('Rating Distribution')\n",
    "Text(0.5, 1.0, 'Rating Distribution')\n",
    "\n",
    "Insight:\n",
    "\n",
    "We can infer from above that most of the ratings are within 3.5 and 4.5\n",
    "3.5 Location\n",
    "plt.figure(figsize=  (20,40))\n",
    "chains = df['location'].value_counts()#[:20]\n",
    "sns.barplot(x = chains, y=  chains.index,  palette= 'deep')\n",
    "plt.title('Loaction of restaurants in bangalore')\n",
    "plt.show()\n",
    "\n",
    "Insight:\n",
    "\n",
    "Here above we can see that most of the restaurants located in 'Koramangala 5th Block', 'BTM' & 'Indiranagar'.\n",
    "Then least restaurants are located 'KR Puram', 'Kanakapura', 'Magadi Road'.\n",
    "3.6 Restaurant Type\n",
    "plt.figure(figsize = (20,40))\n",
    "t = df['rest_type'].value_counts()\n",
    "sns.barplot(y = t.index ,x = t, palette = 'Paired')\n",
    "plt.title('Restaurant Type')\n",
    "plt.show()\n",
    "plt.show()\n",
    "\n",
    "Insight:\n",
    "\n",
    "'Casual Dining', 'Quick Bites', 'Cafe', 'Dessert Parlor' are the most common types of restaurant.\n",
    "'Food Court, Casual Dining', 'Dhaba' are the least common.\n",
    "3.7 Most Liked Dishes\n",
    "import re\n",
    "\n",
    "df.index=range(df.shape[0])\n",
    "likes=[]\n",
    "for i in range(df.shape[0]):\n",
    "    array_split=re.split(',',df['dish_liked'][i])\n",
    "    for item in array_split:\n",
    "        likes.append(item)\n",
    "favourite_food = pd.Series(likes).value_counts()\n",
    "favourite_food.head(30)\n",
    " Pasta              2692\n",
    " Pizza              1915\n",
    " Cocktails          1880\n",
    " Burgers            1736\n",
    " Mocktails          1623\n",
    " Biryani            1307\n",
    " Sandwiches         1287\n",
    "Burgers             1256\n",
    " Coffee             1184\n",
    " Nachos             1170\n",
    " Fish               1116\n",
    " Paratha            1107\n",
    " Salads             1055\n",
    " Chicken Biryani    1004\n",
    "Cocktails            891\n",
    " Fries               876\n",
    " Noodles             854\n",
    " Beer                835\n",
    " Mutton Biryani      832\n",
    " Tea                 819\n",
    "Coffee               801\n",
    " Sandwich            788\n",
    " Butter Chicken      782\n",
    " Thali               770\n",
    "Biryani              749\n",
    "Pizza                747\n",
    " Roti                729\n",
    " Brownie             726\n",
    " Salad               677\n",
    " Hot Chocolate       672\n",
    "dtype: int64\n",
    "cmap = plt.get_cmap('Set3')\n",
    "color = cmap(np.arange(len(v)))\n",
    "\n",
    "ax = favourite_food.nlargest(n = 20, keep = 'first').plot(kind = 'bar', figsize = (18,10), title=  'Top 30 Favourite Food counts', color =  color)\n",
    "\n",
    "for i in ax.patches:\n",
    "    ax.annotate(str(i.get_height()), (i.get_x() * 1.005, i.get_height() * 1.005))\n",
    "    \n",
    "\n",
    "Insights:\n",
    "\n",
    "here form above we can see that pasta & Pizza most famous food in bangalore restaurants.\n",
    "3.8 Most popular cuisines of Bangalore\n",
    "v = df['cuisines'].value_counts()[:15]\n",
    "plt.figure(figsize = (20,8))\n",
    "\n",
    "ax  = sns.barplot(x = v.index, y = v, palette = 'Paired')\n",
    "\n",
    "for i in ax.patches:\n",
    "    ax.annotate(i.get_height().astype(int), (i.get_x()*1.005, i.get_height()*1.005))\n",
    "\n",
    "\n",
    "plt.title('Most popular cuisines of Bangalore', fontsize = 20)\n",
    "plt.xlabel('Cuisines', fontsize = 15)\n",
    "plt.ylabel('Frequency', fontsize = 15)\n",
    "plt.xticks(rotation =90)\n",
    "plt.show()\n",
    "\n",
    "Insights:\n",
    "\n",
    "Here form above we can see that North Indian Cuisines are most famous in bangalore restaurants.\n",
    "3.9 Distribution of Cost of Food for two People\n",
    "contains the approximate cost of meal for two people\n",
    "plt.figure(figsize=(20,8))\n",
    "sns.distplot(df['cost'])\n",
    "plt.show()\n",
    "\n",
    "df.columns\n",
    "Index(['address', 'name', 'online_order', 'book_table', 'rate', 'votes',\n",
    "       'location', 'rest_type', 'dish_liked', 'cuisines', 'cost',\n",
    "       'reviews_list', 'menu_item', 'type', 'city'],\n",
    "      dtype='object')\n",
    "v = df['cost'].value_counts()\n",
    "plt.figure(figsize = (20,8))\n",
    "\n",
    "sns.barplot(x = v.index, y = v, palette = 'Paired')\n",
    "plt.xticks(rotation  =90)\n",
    "plt.show()\n",
    "\n",
    "Insights:\n",
    "\n",
    "Here form above we can that most common price for two person is 400 in bangalore restaurants.\n",
    "3.10 Services Types\n",
    "#Types of Services\n",
    "\n",
    "ax  = sns.countplot(df['type']).set_xticklabels(sns.countplot(df['type']).get_xticklabels(), rotation=90, ha=\"right\")\n",
    "fig = plt.gcf()\n",
    "fig.set_size_inches(12,12)\n",
    "\n",
    "plt.title('Type of Service')\n",
    "plt.show()\n",
    "\n",
    "Insights:\n",
    "\n",
    "Here the two main service types are Delivery and Dine-out.\n",
    "3.11 Highest vote of restaurant\n",
    "name_grp = df.groupby('name')\n",
    "v = name_grp['votes'].agg(np.sum).sort_values(ascending = False)[:20]  ## Here i selected 20 restaurant based on high votes\n",
    "\n",
    "plt.figure(figsize = (20,10))\n",
    "ax = sns.barplot(y = v, x = v.index)\n",
    "\n",
    "for i in ax.patches:\n",
    "    ax.annotate(i.get_height().astype(int), (i.get_x()* 1.005, i.get_height()*1.005))\n",
    "\n",
    "\n",
    "plt.title('Highest vote of restaurant', fontsize = 20)\n",
    "plt.xlabel('Restaurant', fontsize = 15)\n",
    "plt.ylabel('Frequecy', fontsize = 15)\n",
    "plt.xticks(rotation =90)\n",
    "plt.show()\n",
    "\n",
    "Insights:\n",
    "\n",
    "Here from the analysis, we can see that 'Onesta', 'Truffles' & 'Empire Restaurant' are highly voted restaurants.\n",
    "4. Data preparing\n",
    "df.head()\n",
    "address\tname\tonline_order\tbook_table\trate\tvotes\tlocation\trest_type\tdish_liked\tcuisines\tcost\treviews_list\tmenu_item\ttype\tcity\n",
    "0\t942, 21st Main Road, 2nd Stage, Banashankari, ...\tJalsa\tYes\tYes\t4.1\t775\tBanashankari\tCasual Dining\tPasta, Lunch Buffet, Masala Papad, Paneer Laja...\tNorth Indian, Mughlai, Chinese\t800.0\t[('Rated 4.0', 'RATED\\n A beautiful place to ...\t[]\tBuffet\tBanashankari\n",
    "1\t2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...\tSpice Elephant\tYes\tNo\t4.1\t787\tBanashankari\tCasual Dining\tMomos, Lunch Buffet, Chocolate Nirvana, Thai G...\tChinese, North Indian, Thai\t800.0\t[('Rated 4.0', 'RATED\\n Had been here for din...\t[]\tBuffet\tBanashankari\n",
    "2\t1112, Next to KIMS Medical College, 17th Cross...\tSan Churro Cafe\tYes\tNo\t3.8\t918\tBanashankari\tCafe, Casual Dining\tChurros, Cannelloni, Minestrone Soup, Hot Choc...\tCafe, Mexican, Italian\t800.0\t[('Rated 3.0', \"RATED\\n Ambience is not that ...\t[]\tBuffet\tBanashankari\n",
    "3\t1st Floor, Annakuteera, 3rd Stage, Banashankar...\tAddhuri Udupi Bhojana\tNo\tNo\t3.7\t88\tBanashankari\tQuick Bites\tMasala Dosa\tSouth Indian, North Indian\t300.0\t[('Rated 4.0', \"RATED\\n Great food and proper...\t[]\tBuffet\tBanashankari\n",
    "4\t10, 3rd Floor, Lakshmi Associates, Gandhi Baza...\tGrand Village\tNo\tNo\t3.8\t166\tBasavanagudi\tCasual Dining\tPanipuri, Gol Gappe\tNorth Indian, Rajasthani\t600.0\t[('Rated 4.0', 'RATED\\n Very good restaurant ...\t[]\tBuffet\tBanashankari\n",
    "4.1 Convert the online categorical variables into a numeric format\n",
    "df.online_order[df.online_order == 'Yes'] = 1\n",
    "df.online_order[df.online_order == 'No'] =  0\n",
    "df.online_order.value_counts()\n",
    "1    16378\n",
    "0     6870\n",
    "Name: online_order, dtype: int64\n",
    "4.2 Label Encoding\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "le = LabelEncoder()\n",
    "df.location = le.fit_transform(df.location)\n",
    "df.rest_type = le.fit_transform(df.rest_type)\n",
    "df.cuisines = le.fit_transform(df.cuisines)\n",
    "df.menu_item = le.fit_transform(df.menu_item)\n",
    "\n",
    "df.book_table = le.fit_transform(df.book_table)\n",
    "df.head(n=2)\n",
    "address\tname\tonline_order\tbook_table\trate\tvotes\tlocation\trest_type\tdish_liked\tcuisines\tcost\treviews_list\tmenu_item\ttype\tcity\n",
    "0\t942, 21st Main Road, 2nd Stage, Banashankari, ...\tJalsa\t1\t1\t4.1\t775\t1\t20\tPasta, Lunch Buffet, Masala Papad, Paneer Laja...\t1386\t800.0\t[('Rated 4.0', 'RATED\\n A beautiful place to ...\t5047\tBuffet\tBanashankari\n",
    "1\t2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...\tSpice Elephant\t1\t0\t4.1\t787\t1\t20\tMomos, Lunch Buffet, Chocolate Nirvana, Thai G...\t594\t800.0\t[('Rated 4.0', 'RATED\\n Had been here for din...\t5047\tBuffet\tBanashankari\n",
    "my_data = df.iloc[:,[2,3,4,5,6,7,9,10,12]]\n",
    "\n",
    "my_data.to_csv('Zomato_df.csv')\n",
    "my_data.head()\n",
    "online_order\tbook_table\trate\tvotes\tlocation\trest_type\tcuisines\tcost\tmenu_item\n",
    "0\t1\t1\t4.1\t775\t1\t20\t1386\t800.0\t5047\n",
    "1\t1\t0\t4.1\t787\t1\t20\t594\t800.0\t5047\n",
    "2\t1\t0\t3.8\t918\t1\t16\t484\t800.0\t5047\n",
    "3\t0\t0\t3.7\t88\t1\t62\t1587\t300.0\t5047\n",
    "4\t0\t0\t3.8\t166\t4\t20\t1406\t600.0\t5047\n",
    "plt.figure(figsize = (20,20))\n",
    "sns.heatmap(my_data.corr(), annot = True)\n",
    "plt.show()\n",
    "\n",
    "Insights:\n",
    "\n",
    "Here from the above we can see that rate is higly correlated with votes.\n",
    "4.3 Depedent and independent variable\n",
    "X = df.iloc[:,[2,3,5,6,7,9,10,12]]\n",
    "y = df['rate']\n",
    "X\n",
    "online_order\tbook_table\tvotes\tlocation\trest_type\tcuisines\tcost\tmenu_item\n",
    "0\t1\t1\t775\t1\t20\t1386\t800.0\t5047\n",
    "1\t1\t0\t787\t1\t20\t594\t800.0\t5047\n",
    "2\t1\t0\t918\t1\t16\t484\t800.0\t5047\n",
    "3\t0\t0\t88\t1\t62\t1587\t300.0\t5047\n",
    "4\t0\t0\t166\t4\t20\t1406\t600.0\t5047\n",
    "...\t...\t...\t...\t...\t...\t...\t...\t...\n",
    "23243\t1\t1\t128\t84\t5\t1318\t1200.0\t5047\n",
    "23244\t0\t0\t77\t84\t38\t878\t2000.0\t5047\n",
    "23245\t0\t0\t161\t84\t21\t539\t1200.0\t5047\n",
    "23246\t0\t0\t81\t84\t21\t80\t800.0\t5047\n",
    "23247\t0\t1\t236\t25\t4\t878\t2500.0\t5047\n",
    "23248 rows × 8 columns\n",
    "\n",
    " \n",
    "y\n",
    "0        4.1\n",
    "1        4.1\n",
    "2        3.8\n",
    "3        3.7\n",
    "4        3.8\n",
    "        ... \n",
    "23243    3.8\n",
    "23244    3.9\n",
    "23245    2.8\n",
    "23246    2.5\n",
    "23247    4.3\n",
    "Name: rate, Length: 23248, dtype: float64\n",
    "4.4 Splitting data into train and test set\n",
    "from sklearn.model_selection import train_test_split\n",
    "X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=10)\n",
    "X_train\n",
    "online_order\tbook_table\tvotes\tlocation\trest_type\tcuisines\tcost\tmenu_item\n",
    "17097\t1\t1\t232\t49\t5\t122\t2000.0\t5047\n",
    "5558\t1\t1\t3485\t48\t61\t646\t1700.0\t5047\n",
    "22590\t1\t1\t977\t71\t57\t669\t1500.0\t1171\n",
    "4803\t0\t0\t118\t30\t20\t1185\t800.0\t5047\n",
    "21701\t0\t1\t497\t65\t54\t1124\t2000.0\t5047\n",
    "...\t...\t...\t...\t...\t...\t...\t...\t...\n",
    "9372\t1\t1\t871\t30\t20\t1296\t900.0\t5047\n",
    "7291\t1\t0\t450\t22\t20\t1209\t550.0\t5047\n",
    "17728\t0\t1\t592\t67\t20\t1156\t1200.0\t5047\n",
    "7293\t0\t0\t196\t38\t29\t838\t500.0\t5047\n",
    "17673\t0\t0\t122\t48\t21\t1304\t1200.0\t5047\n",
    "16273 rows × 8 columns\n",
    "\n",
    "y_train\n",
    "17097    4.4\n",
    "5558     4.3\n",
    "22590    4.0\n",
    "4803     3.9\n",
    "21701    4.3\n",
    "        ... \n",
    "9372     4.0\n",
    "7291     3.9\n",
    "17728    4.3\n",
    "7293     3.8\n",
    "17673    3.1\n",
    "Name: rate, Length: 16273, dtype: float64\n",
    "5 Modeling\n",
    "5.1 Linear Regression\n",
    "from sklearn.linear_model import LinearRegression\n",
    "lr = LinearRegression()\n",
    "lr.fit(X_train,y_train)\n",
    "\n",
    "#predict the test set\n",
    "y_pred = lr.predict(X_test)\n",
    "\n",
    "## Evaluate the model\n",
    "from sklearn.metrics import r2_score\n",
    "print(r2_score(y_test, y_pred))\n",
    "0.22818828522967072\n",
    " \n",
    "5.2 Decision Tree Regression\n",
    "from sklearn.tree import DecisionTreeRegressor\n",
    "dtr = DecisionTreeRegressor(min_samples_leaf=0.01)\n",
    "\n",
    "dtr.fit(X_train,y_train)\n",
    "\n",
    "# Predict the test ser\n",
    "y_pred  = dtr.predict(X_test)\n",
    "\n",
    "# Evaluate the model performance\n",
    "from sklearn.metrics import r2_score\n",
    "\n",
    "print(r2_score(y_test,y_pred))\n",
    "0.3741898389426611\n",
    "5.3 Random Forest Regressor\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "rfr = RandomForestRegressor(n_estimators=650,random_state=245,min_samples_leaf=.0001)\n",
    "rfr.fit(X_train,y_train)\n",
    "\n",
    "# Predict the test ser\n",
    "y_pred  = rfr.predict(X_test)\n",
    "\n",
    "# Evaluate the model performance\n",
    "from sklearn.metrics import r2_score\n",
    "\n",
    "print(r2_score(y_test,y_pred))\n",
    "0.8809706960047533\n",
    "5.4 Support vector Regressor\n",
    "from sklearn.svm import SVR\n",
    "svr = SVR(kernel ='rbf')\n",
    "\n",
    "svr.fit(X_train, y_train)\n",
    "\n",
    "# predict the test set\n",
    "y_pred = svr.predict(X_test)\n",
    "\n",
    "\n",
    "from sklearn.metrics import r2_score\n",
    "r2 = r2_score(y_test, y_pred)\n",
    "print(r2)\n",
    "0.24327610722747994\n",
    " \n",
    "\n",
    "\n",
    "from sklearn.ensemble import ExtraTreesRegressor\n",
    "etr = ExtraTreesRegressor(n_estimators = 120)\n",
    "\n",
    "etr.fit(X_train, y_train)\n",
    "\n",
    "\n",
    "y_pred = etr.predict(X_test)\n",
    "\n",
    "from sklearn.metrics import r2_score\n",
    "r2 = r2_score(y_test,y_pred)\n",
    "print(r2)\n",
    "0.933027981873644\n",
    "\n",
    " "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
